### ISSUE TITLE
Uploading Images for wiki 

### ISSUE THREAD

**Issue by simon-estill** [smbc-digital/form-builder#132]
### Description
![success](https://user-images.githubusercontent.com/19569720/87535268-2022dc80-c68f-11ea-91fa-e3c43173dffc.png)
![page1](https://user-images.githubusercontent.com/19569720/87535282-23b66380-c68f-11ea-98db-27e10c0079e6.png)

![page0](https://user-images.githubusercontent.com/19569720/87535245-18fbce80-c68f-11ea-8f1a-90c98f97a11a.png)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
- vX.X.X

**Comment by lallysmbc** [comment]
@simon-estill can i close this, was this opened on accident?

**Comment by simon-estill** [comment]
![summary-no-edit](https://user-images.githubusercontent.com/19569720/87683151-a109d300-c778-11ea-87ed-93bfa622e772.png)
![summary-apples](https://user-images.githubusercontent.com/19569720/87683197-ae26c200-c778-11ea-9108-b128842d2dd6.png)
