### ISSUE TITLE
ASP Core 5 , Screenshots and setup help, 

### ISSUE THREAD

**Issue by weedkiller** [smbc-digital/form-builder#410]
hello can you please add some help and screen shots,

how to initialize db, user login

also asp .NET core 5 and BS 5, updates

**Comment by lallysmbc** [comment]
Hi,

.NET core 5 upgrade is on our backlog currently but is not a priority at the current time. We do not have any db or user login so i am not sure if you are referring to Storage providers if so you can have a read of this section about how to confiure or add additonal storage providers.
https://github.com/smbc-digital/form-builder#storage-providers

For help on building a form you can look at our wiki the basic guide within there will walk you through how to build a basic form

https://github.com/smbc-digital/form-builder/wiki
